export 'find_largest_list_element.dart';
export 'sum_all_list_elements.dart';
export 'sum_of_even_list_elements.dart';
export 'arithmetic_mean_of_all_elements_list.dart';
export 'list_in_reverse.dart';
export 'outputs_not_even_list_elements .dart';
export 'get_smallest_element_in_list.dart';
export 'check_list_contains_given_element.dart';
export 'find_element_which_larger_then_previous.dart';
export 'find_duplicates_in_list.dart';
export 'removes_specified_element.dart';
export 'check_list_is_palindrome.dart';
